"""purchase_flow

Revision ID: 7acb41dba265
Revises: 0001_baseline
Create Date: 2026-02-27 19:24:03.951758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acb41dba265'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount_cent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    op.add_column('order_items', sa.Column('product_name', sa.String(length=120), nullable=False))
    op.add_column('order_items', sa.Column('sku_name', sa.String(length=120), nullable=False))
    op.add_column('order_items', sa.Column('image_url', sa.String(length=500), nullable=False))
    op.add_column('orders', sa.Column('address_id', sa.String(length=36), nullable=False))
    op.add_column('orders', sa.Column('address_snapshot', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address_snapshot')
    op.drop_column('orders', 'address_id')
    op.drop_column('order_items', 'image_url')
    op.drop_column('order_items', 'sku_name')
    op.drop_column('order_items', 'product_name')
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
